package task.walletapi.exception;

public class RetryableException extends RuntimeException{
    public RetryableException(Throwable cause) {
        super(cause);
    }
}
